/**
 * EngagementLeaderboard — top 10 Quiz+Tap+Wheel combined (this week).
 *
 * Appears on the Games hub. Includes a "Partager mon rang" button that
 * triggers the Web Share API with a PNG generated by the backend
 * (/api/engagement/share-card.png).
 */
import { useEffect, useState } from 'react';
import axios from 'axios';
import { toast } from 'sonner';
import { Trophy, Crown, Share, Target, Question, HandTap } from '@phosphor-icons/react';
import { useAuth } from '@/context/AuthContext';

const API = process.env.REACT_APP_BACKEND_URL;

export default function EngagementLeaderboard() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [sharing, setSharing] = useState(false);

  useEffect(() => {
    axios.get(`${API}/api/engagement/leaderboard/weekly`, { withCredentials: true })
      .then(({ data }) => setData(data))
      .catch(() => {});
  }, []);

  const share = async () => {
    if (!user) return;
    setSharing(true);
    try {
      const res = await fetch(`${API}/api/engagement/share-card.png`, {
        credentials: 'include',
        cache: 'no-store',
      });
      if (!res.ok) throw new Error('share-card fetch failed');
      const blob = await res.blob();
      const file = new File([blob], 'japap-classement.png', { type: 'image/png' });
      // iter168 — brand-correct domain (was hardcoded japap.app)
      const shareUrl = window.location.origin || 'https://japapmessenger.com';
      const shareText = `Je suis #${data?.me?.rank ?? '?'} au classement JAPAP cette semaine 🏆 Rejoins-moi ! ${shareUrl}`;

      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'Mon rang JAPAP',
          text: shareText,
        });
      } else {
        // Fallback — download + open WhatsApp intent
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = 'japap-classement.png';
        document.body.appendChild(a); a.click(); a.remove();
        URL.revokeObjectURL(url);
        window.open(`https://wa.me/?text=${encodeURIComponent(shareText)}`, '_blank');
        toast.success('Image téléchargée, partage WhatsApp ouvert.');
      }
    } catch (e) {
      toast.error('Partage impossible');
    } finally { setSharing(false); }
  };

  if (!data) return null;
  const { top, me } = data;

  return (
    <div className="jp-card-elevated p-5" data-testid="engagement-leaderboard">
      <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
        <h3 className="font-['Outfit'] text-lg font-bold flex items-center gap-2"
            style={{ color: 'var(--jp-text)' }}>
          <Trophy size={20} style={{ color: '#F59E0B' }} weight="fill" />
          Classement de la semaine
        </h3>
        {me && user && (
          <button onClick={share} disabled={sharing}
                  data-testid="share-rank-btn"
                  className="jp-btn jp-btn-sm jp-btn-primary inline-flex items-center gap-1.5">
            <Share size={14} weight="bold" />
            {sharing ? 'Partage…' : `Partager mon rang #${me.rank}`}
          </button>
        )}
      </div>

      {top.length === 0 ? (
        <div className="py-6 text-center text-sm" style={{ color: 'var(--jp-text-muted)' }}>
          Aucune activité cette semaine — jouez pour entrer au classement !
        </div>
      ) : (
        <div className="space-y-2">
          {top.map((p) => (
            <Row key={p.user_id} player={p}
                 mine={user?.user_id === p.user_id} />
          ))}
        </div>
      )}

      {me && user && !top.some((p) => p.user_id === user.user_id) && (
        <div className="mt-4 pt-4 border-t" style={{ borderColor: 'var(--jp-border)' }}>
          <div className="flex items-center gap-3 p-3 rounded-xl"
               style={{ background: 'rgba(255,215,0,0.10)', border: '1px solid rgba(255,215,0,0.35)' }}
               data-testid="leaderboard-me-row">
            <span className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold"
                  style={{ background: 'rgba(255,215,0,0.3)', color: '#9A6700' }}>
              #{me.rank}
            </span>
            <div className="flex-1 font-['Manrope'] text-sm font-medium">Votre rang</div>
            <div className="font-['Outfit'] font-bold" style={{ color: '#F59E0B' }}>
              +{me.points_total.toLocaleString('fr-FR')} pts
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Row({ player, mine }) {
  const { rank } = player;
  const medal = rank === 1 ? '#FFD700' : rank === 2 ? '#C0C0C0' : rank === 3 ? '#CD7F32' : null;
  return (
    <div className="flex items-center gap-3 p-3 rounded-xl"
         style={{
           background: mine ? 'rgba(15,5,107,0.08)' : 'var(--jp-surface-secondary)',
           border: mine ? '1px solid rgba(15,5,107,0.3)' : '1px solid transparent',
         }}
         data-testid={`leaderboard-row-${player.user_id}`}>
      <span className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold font-['Outfit']"
            style={{
              background: medal || 'var(--jp-surface)',
              color: medal ? '#000' : 'var(--jp-text)',
            }}>
        {rank <= 3 ? <Crown size={14} weight="fill" /> : rank}
      </span>
      <div className="jp-avatar jp-avatar-sm" style={{ background: 'var(--jp-primary)', color: '#fff' }}>
        {player.avatar ? <img src={player.avatar} alt="" /> : (player.name?.[0] || '?').toUpperCase()}
      </div>
      <div className="flex-1 min-w-0">
        <div className="text-sm font-semibold font-['Manrope'] truncate"
             style={{ color: 'var(--jp-text)' }}>
          {player.name}
          {player.is_pro && (
            <span className="ml-1.5 text-[10px] font-bold px-1.5 py-0.5 rounded"
                  style={{ background: '#FFD70033', color: '#9A6700' }}>PRO</span>
          )}
        </div>
        <div className="flex items-center gap-2 text-[10px] mt-0.5"
             style={{ color: 'var(--jp-text-muted)' }}>
          <SourceChip icon={Target} value={player.points_wheel} color="#F59E0B" />
          <SourceChip icon={Question} value={player.points_quiz} color="#8B5CF6" />
          <SourceChip icon={HandTap} value={player.points_tap} color="#E01C2E" />
        </div>
      </div>
      <div className="text-right">
        <div className="font-['Outfit'] text-sm font-bold" style={{ color: 'var(--jp-secondary)' }}>
          +{player.points_total.toLocaleString('fr-FR')}
        </div>
        <div className="text-[10px]" style={{ color: 'var(--jp-text-muted)' }}>
          {player.days_played}j joués
        </div>
      </div>
    </div>
  );
}

function SourceChip({ icon: Icon, value, color }) {
  if (!value) return null;
  return (
    <span className="inline-flex items-center gap-0.5">
      <Icon size={10} weight="fill" style={{ color }} />
      {value}
    </span>
  );
}
